from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from io import BytesIO
from datetime import datetime

def generate_shopping_list_pdf(items, user_name="User"):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    story = []
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#768A76'),
        spaceAfter=30,
    )
    
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Normal'],
        fontSize=12,
        textColor=colors.HexColor('#5C5852'),
        spaceAfter=20,
    )
    
    # Title
    story.append(Paragraph("Chef Feels Shopping List", title_style))
    story.append(Paragraph(f"Prepared for: {user_name}", subtitle_style))
    story.append(Paragraph(f"Date: {datetime.now().strftime('%B %d, %Y')}", subtitle_style))
    story.append(Spacer(1, 0.3 * inch))
    
    # Items table
    if items:
        # Separate checked and unchecked items
        unchecked = [item for item in items if not item.get('checked', False)]
        checked = [item for item in items if item.get('checked', False)]
        
        if unchecked:
            story.append(Paragraph("To Buy:", styles['Heading2']))
            story.append(Spacer(1, 0.1 * inch))
            
            data = [["☐", item['name']] for item in unchecked]
            table = Table(data, colWidths=[0.5*inch, 5*inch])
            table.setStyle(TableStyle([
                ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 11),
                ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#2D2A26')),
                ('LEFTPADDING', (0, 0), (-1, -1), 6),
                ('RIGHTPADDING', (0, 0), (-1, -1), 6),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ]))
            story.append(table)
            story.append(Spacer(1, 0.3 * inch))
        
        if checked:
            story.append(Paragraph("Already Checked:", styles['Heading2']))
            story.append(Spacer(1, 0.1 * inch))
            
            data = [["☑", item['name']] for item in checked]
            table = Table(data, colWidths=[0.5*inch, 5*inch])
            table.setStyle(TableStyle([
                ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 11),
                ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#5C5852')),
                ('LEFTPADDING', (0, 0), (-1, -1), 6),
                ('RIGHTPADDING', (0, 0), (-1, -1), 6),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ]))
            story.append(table)
    else:
        story.append(Paragraph("No items in shopping list.", styles['Normal']))
    
    # Footer
    story.append(Spacer(1, 0.5 * inch))
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.HexColor('#5C5852'),
        alignment=1,  # Center
    )
    story.append(Paragraph("Generated by Chef Feels - Cook What You Feel", footer_style))
    
    doc.build(story)
    buffer.seek(0)
    return buffer